// apps/vue/src/components/ItemCard.vue
<template>
  <div class="border p-4 rounded shadow-sm bg-white space-y-1">
    <p class="text-lg font-semibold">{{ item.name }}</p>
    <component :is="Renderer" :item="item" />
  </div>
</template>

<script setup lang="ts">
import type { ListItem } from '@shared/types'
import { itemRenderers } from '../renderers/item-renderers'

const props = defineProps<{ item: ListItem }>()

const Renderer = itemRenderers[props.item.kind]
</script>

// apps/react/src/components/ItemCard.tsx
import type { ListItem, TypedListItem, ListItemKindMap } from '@shared/types'
import { getBotTotalCost } from '@shared/utils/item-utils'

interface Props {
  item: ListItem
}

type Renderer<K extends keyof ListItemKindMap> = (
  item: TypedListItem<K>
) => React.ReactNode

const renderers: {
  [K in keyof ListItemKindMap]: Renderer<K>
} = {
  user: (item) => (
    <>
      <p>Email: {item.data.email}</p>
      <p>Birth: {item.data.birth}</p>
    </>
  ),
  bot: (item) => (
    <>
      <p>Tokens: {item.data.tokens}</p>
      <p>Cost: {getBotTotalCost(item)}</p>
    </>
  ),

  // Future kinds here...
}

const UnknownRenderer = () => (
  <p className="text-gray-500 italic">Unknown item type</p>
)

export default function ItemCard({ item }: Props) {
  const render = renderers[item.kind as keyof ListItemKindMap] ?? UnknownRenderer

  return (
    <div className="border p-4 rounded shadow-sm bg-white space-y-1">
      <p className="text-lg font-semibold">{item.name}</p>
      {render(item as any)}
    </div>
  )
}
